import Foundation
import os

/// The blank iWork documents the app copies for “New File → Pages/Numbers/Keynote”,
/// and the single place that decides whether a kind can be created at all.
///
/// Word/Excel/PowerPoint need no template: `OOXMLDocumentFactory` writes their
/// packages. Pages/Numbers/Keynote are closed formats (IWA/protobuf inside a
/// package), so they are **copied** from a blank document the user saves once
/// into `MenuRight/Resources/Templates/`. A missing template hides the menu item
/// instead of offering an action that can only fail (P6 scope: "模板缺失时该项隐藏并提示").
///
/// The directory is injectable so the unit tests never need a bundled template.
enum DocumentTemplateCatalog {
    static let log = Logger(subsystem: "xin.ljhsu.MenuRight", category: "document-templates")

    /// Subdirectory of the app bundle's `Resources`, added as a **folder
    /// reference** in the Xcode project so dropping a file in is enough — no
    /// project edit per template.
    static let bundleSubdirectory = "Templates"

    /// File name expected in the template directory, or nil for kinds that are
    /// generated rather than copied.
    static func templateFileName(for type: NewFileType) -> String? {
        switch type {
        case .pages: return "blank.pages"
        case .numbers: return "blank.numbers"
        case .keynote: return "blank.key"
        case .text, .markdown, .html, .css, .javascript, .json,
             .docx, .xlsx, .pptx:
            return nil
        }
    }

    /// `Contents/Resources/Templates` of the running main app.
    static var bundledDirectory: URL? {
        Bundle.main.resourceURL?.appendingPathComponent(bundleSubdirectory, isDirectory: true)
    }

    /// Resolved template URL, or nil when the file is not there.
    ///
    /// `fileExists` works for both shapes an iWork document can have on disk: a
    /// package directory (the usual case on APFS) and a flat file (non-HFS
    /// volume). Copying is delegated to `FileManager.copyItem`, which preserves
    /// whichever it is.
    static func templateURL(for type: NewFileType, in directory: URL?) -> URL? {
        guard let fileName = templateFileName(for: type), let directory else { return nil }
        let url = directory.appendingPathComponent(fileName)
        guard FileManager.default.fileExists(atPath: url.path) else { return nil }
        return url
    }

    /// Whether this build can create `type` right now.
    static func canCreate(_ type: NewFileType, in directory: URL?) -> Bool {
        switch type.category {
        case .text, .office:
            // Generated by the extension (text) or by this app (OOXML).
            return true
        case .iWork:
            return templateURL(for: type, in: directory) != nil
        }
    }

    static func creatableTypes(in directory: URL?) -> Set<NewFileType> {
        Set(NewFileType.allCases.filter { canCreate($0, in: directory) })
    }

    /// Template-backed kinds this build cannot create, in catalog order.
    static func missingTemplateTypes(in directory: URL?) -> [NewFileType] {
        NewFileType.allCases.filter { $0.category == .iWork && !canCreate($0, in: directory) }
    }

    /// Computes and publishes `NewFileAvailability`, and returns it.
    ///
    /// Called once at launch (the answer cannot change while the app runs — the
    /// templates are inside the app bundle) so `FinderSync.menu(for:)` never has
    /// to touch the filesystem.
    @discardableResult
    static func publishAvailability(
        bundle: Bundle = .main,
        defaults: UserDefaults = SettingsStore.defaultUserDefaults()
    ) -> NewFileAvailability {
        publishAvailability(
            directory: bundle.resourceURL?.appendingPathComponent(bundleSubdirectory, isDirectory: true),
            defaults: defaults
        )
    }

    /// Directory-injectable seam: the unit tests publish from a scratch folder,
    /// never from the test runner's own bundle.
    @discardableResult
    static func publishAvailability(
        directory: URL?,
        defaults: UserDefaults
    ) -> NewFileAvailability {
        let creatable = NewFileType.allCases
            .filter { canCreate($0, in: directory) }
            .map(\.rawValue)
        let availability = NewFileAvailability(creatableTypes: creatable)
        availability.write(to: defaults)

        let missing = missingTemplateTypes(in: directory).map(\.rawValue)
        log.notice(
            "published new-file availability creatable=\(creatable.joined(separator: ","), privacy: .public) missingTemplates=\(missing.joined(separator: ","), privacy: .public) directory=\(directory?.path ?? "<none>", privacy: .public)"
        )
        return availability
    }
}
