import Foundation

/// Templates for "New File". Phase P6 covers the text formats; the document
/// formats (Word/Excel/PPT/Pages/Numbers/Keynote) arrive in P6-b and are backed
/// by OOXML generation + bundled templates.
///
/// The raw values intentionally equal `NewFileType`'s (the settings catalog, not
/// compiled into this extension), so the published availability payload and the
/// wire contract can be matched by string without a translation table. A test
/// pins that equality.
enum NewFileKind: String, CaseIterable, Equatable {
    case text
    case markdown
    case html
    case css
    case javascript
    case json
    // P6-b: generated by the main app (`OOXMLDocumentFactory`).
    case docx
    case xlsx
    case pptx
    // P6-b: copied from a blank template in the main app bundle.
    case pages
    case numbers
    case keynote

    /// Where a kind's bytes come from. Decides both the wire request and whether
    /// the menu can offer it at all.
    enum Category: Equatable {
        /// Generated in the extension itself (`contents`), no dependency.
        case text
        /// Written by the main app as an OOXML package.
        case office
        /// Copied by the main app from a bundled blank document.
        case iWork
    }

    var category: Category {
        switch self {
        case .text, .markdown, .html, .css, .javascript, .json: return .text
        case .docx, .xlsx, .pptx: return .office
        case .pages, .numbers, .keynote: return .iWork
        }
    }

    /// Kinds that need nothing from the main app beyond a name: they stay in the
    /// menu even before the app has published an availability payload.
    static var textKinds: [NewFileKind] {
        allCases.filter { $0.category == .text }
    }

    /// The kinds the submenu may offer, given what the main app published.
    ///
    /// `nil` (the app has never published — fresh install, first launch after an
    /// update) falls back to the text kinds: offering a document kind that the
    /// running app cannot create would produce a guaranteed-failure menu item,
    /// which is exactly what the P6 scope forbids.
    static func available(from availability: NewFileAvailability?) -> [NewFileKind] {
        guard let availability else { return textKinds }
        return allCases.filter { $0.category == .text || availability.canCreate($0.rawValue) }
    }

    /// The wording shared with 新建文件, so the submenu and the settings pane
    /// cannot drift apart.
    var titleKey: StringKey {
        switch self {
        case .text: return .newFileKindText
        case .markdown: return .newFileKindMarkdown
        case .html: return .newFileKindHTML
        case .css: return .newFileKindCSS
        case .javascript: return .newFileKindJavaScript
        case .json: return .newFileKindJSON
        case .docx: return .newFileKindWord
        case .xlsx: return .newFileKindExcel
        case .pptx: return .newFileKindPowerPoint
        case .pages: return .newFileKindPages
        case .numbers: return .newFileKindNumbers
        case .keynote: return .newFileKindKeynote
        }
    }

    /// Menu title in the language the settings UI is currently using.
    func title(in language: AppLanguage) -> String {
        Localization.text(titleKey, language: language)
    }

    var fileExtension: String {
        switch self {
        case .text: return "txt"
        case .markdown: return "md"
        case .html: return "html"
        case .css: return "css"
        case .javascript: return "js"
        case .json: return "json"
        case .docx: return "docx"
        case .xlsx: return "xlsx"
        case .pptx: return "pptx"
        case .pages: return "pages"
        case .numbers: return "numbers"
        case .keynote: return "key"
        }
    }

    var defaultName: String {
        "Untitled.\(fileExtension)"
    }

    /// Initial contents. `nil` means either an empty file (text kinds) or "the
    /// main app decides" (document kinds) — `category` tells the two apart.
    /// The code formats get a minimal, valid skeleton so a new file is
    /// immediately usable.
    var contents: Data? {
        switch self {
        case .text, .markdown, .docx, .xlsx, .pptx, .pages, .numbers, .keynote:
            return nil   // empty file / generated or copied by the main app
        case .html:
            return Data("""
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <title>Untitled</title>
            </head>
            <body>

            </body>
            </html>

            """.utf8)
        case .css:
            return Data("""
            /* Styles */

            body {
            }

            """.utf8)
        case .javascript:
            return Data("\"use strict\";\n".utf8)
        case .json:
            return Data("{}".utf8)
        }
    }
}

/// Menu-item titles, rendered in the language the settings UI currently uses.
///
/// Finder replays an action through a reconstructed `NSMenuItem` that does not
/// carry `representedObject` across the process boundary, so `sender.title` is
/// **the only key** the extension gets back. That is why this type also owns the
/// reverse lookups at the bottom: they accept *every* language, so a menu built
/// just before a language switch still dispatches correctly.
enum FinderMenuTitles {
    /// Title of one actionable item.
    static func title(for action: FinderMenuAction, language: AppLanguage) -> String {
        switch action {
        case .createAlias:
            return Localization.text(.finderMenuCreateAlias, language: language)
        case .setLocked(_, let locked):
            return Localization.text(locked ? .finderMenuLock : .finderMenuUnlock, language: language)
        case .copyName:
            return Localization.text(.filePermissionActionCopyName, language: language)
        case .copyPath:
            return Localization.text(.filePermissionActionCopyPath, language: language)
        case .copyFileURL:
            return Localization.text(.filePermissionActionCopyFileURL, language: language)
        case .cut:
            return Localization.text(.finderMenuCut, language: language)
        case .openTerminal:
            return Localization.text(.filePermissionActionOpenTerminal, language: language)
        case .copyFolderName:
            return Localization.text(.finderMenuCopyFolderName, language: language)
        case .copyFolderPath:
            return Localization.text(.finderMenuCopyFolderPath, language: language)
        case .newFile(let kind, _):
            return kind.title(in: language)
        case .newFolder:
            return Localization.text(.finderMenuNewFolder, language: language)
        case .pasteHere:
            return Localization.text(.finderMenuPasteHere, language: language)
        case .openFavorite(let entry):
            // User data, not a localized string — and the only key Finder hands
            // back on replay, which is why `FinderFavorites` guarantees it is
            // unique across all three lists.
            return entry.menuTitle
        case .extractArchives:
            return Localization.text(.finderMenuExtractHere, language: language)
        case .extractArchivesCustomize:
            return Localization.text(.finderMenuExtractCustom, language: language)
        case .compressItems(_, let format):
            return Self.compressionTitle(forFormat: format, language: language)
        case .compressItemsCustomize:
            return Localization.text(.finderMenuCompressCustom, language: language)
        }
    }

    /// 压缩 ▸ item for a format. Kept in step with
    /// `FinderArchives.compressionFormats` — a format with no wording here still
    /// renders (as "压缩 &lt;FORMAT&gt;"), so the menu can never show an empty label.
    static func compressionTitle(forFormat format: String, language: AppLanguage) -> String {
        switch format {
        case "zip":
            return Localization.text(.finderMenuCompressToZip, language: language)
        case "tar":
            return Localization.text(.finderMenuCompressToTar, language: language)
        case "gzip":
            return Localization.text(.finderMenuCompressToTarGz, language: language)
        case "bzip2":
            return Localization.text(.finderMenuCompressToTarBz2, language: language)
        default:
            return Localization.text(.finderMenuCompress, language: language) + " \(format.uppercased())"
        }
    }

    /// Title of a submenu parent, from the settings wording it shares.
    static func submenuTitle(_ key: StringKey, language: AppLanguage) -> String {
        Localization.text(key, language: language)
    }

    // MARK: - Reverse lookups (title → action)

    /// What `performCopy` should put on the pasteboard.
    enum CopySubject: Equatable {
        case names
        case paths
        case fileURLs
        case folderName
        case folderPath
    }

    static func copySubject(forTitle title: String) -> CopySubject? {
        for language in concreteLanguages {
            if title == Localization.text(.filePermissionActionCopyName, language: language) { return .names }
            if title == Localization.text(.filePermissionActionCopyPath, language: language) { return .paths }
            if title == Localization.text(.filePermissionActionCopyFileURL, language: language) { return .fileURLs }
            if title == Localization.text(.finderMenuCopyFolderName, language: language) { return .folderName }
            if title == Localization.text(.finderMenuCopyFolderPath, language: language) { return .folderPath }
        }
        return nil
    }

    static func isUnlockTitle(_ title: String) -> Bool {
        concreteLanguages.contains { title == Localization.text(.finderMenuUnlock, language: $0) }
    }

    /// True when the clicked 解压 item asks for a destination.
    static func isCustomExtractionTitle(_ title: String) -> Bool {
        concreteLanguages.contains { title == Localization.text(.finderMenuExtractCustom, language: $0) }
    }

    /// True when the clicked 压缩 item is the dialog one.
    static func isCustomCompressionTitle(_ title: String) -> Bool {
        concreteLanguages.contains { title == Localization.text(.finderMenuCompressCustom, language: $0) }
    }

    /// Reverse of `compressionTitle`: the format a clicked 压缩 item means.
    static func compressionFormat(forTitle title: String) -> String? {
        for format in FinderArchives.compressionFormats {
            for language in concreteLanguages where title == compressionTitle(forFormat: format, language: language) {
                return format
            }
        }
        return nil
    }

    static func newFileKind(forTitle title: String) -> NewFileKind? {
        for language in concreteLanguages {
            if let kind = NewFileKind.allCases.first(where: { $0.title(in: language) == title }) {
                return kind
            }
        }
        return nil
    }

    /// `.system` never reaches a menu item — titles are resolved to a concrete
    /// language when the menu is built — so matching only needs the catalogs.
    static var concreteLanguages: [AppLanguage] {
        AppLanguage.allCases.filter { $0 != .system }
    }
}

/// A single actionable item the Finder context menu offers.
enum FinderMenuAction: Equatable {
    // Item selection (flat menu, no submenus — see FinderMenuBuilder.plan).
    case createAlias(items: [URL])
    case setLocked(items: [URL], locked: Bool)
    case copyName(payload: String)
    case copyPath(payload: String)
    case copyFileURL(payload: String)
    case cut(items: [URL])
    // Container / desktop background.
    case openTerminal(directory: URL)
    case copyFolderName(payload: String)
    case copyFolderPath(payload: String)
    case newFile(kind: NewFileKind, directory: URL)
    case newFolder(directory: URL)
    case pasteHere(destination: URL, enabled: Bool)
    /// P7-b: one entry of 常用软件 / 常用网页 / 常用文件夹.
    case openFavorite(entry: FinderFavoriteEntry)
    /// P9: 解压 ▸ — every selected item is an archive. `destination` nil means
    /// "each archive's own folder".
    case extractArchives(archives: [URL], destination: URL?)
    /// P9 stage 4: 解压 ▸ → 解压到指定位置…, which asks the main app for a folder.
    case extractArchivesCustomize(archives: [URL])
    /// P9: 压缩 ▸ — the whole selection, into `format`.
    case compressItems(items: [URL], format: String)
    /// P9 stage 3: 压缩 ▸ → 自定义压缩…, which opens the dialog in the main app.
    case compressItemsCustomize(items: [URL])
}

/// Pure description of the context menu. AppKit only enters at build time in
/// FinderSync; everything here is unit-testable without Finder.
enum FinderMenuPlanItem: Equatable {
    case action(FinderMenuAction)
    case submenu(titleKey: StringKey, actions: [FinderMenuAction])
}

/// Pure mapping from the right-click context to the MenuRight menu.
///
/// Platform note: macOS renders an extension's menu inside its own entry in the
/// Finder context menu, and an extension cannot create top-level items or
/// control where that entry sits. So "same level as MenuRight" is not
/// achievable; what we control is the *content* — and the item-selection case
/// is therefore built completely flat (no submenus) so no cascade appears under
/// our entry, matching the intent of "选中后不再显示级联".
///
/// The branch is decided by the *actual* menu kind (container background vs item
/// selection), NOT by selection.hasSelection: on a container right-click Finder
/// may still report a stale selectedItemURLs() from the window, and selection
/// must never be conflated with the target.
///
/// Item selection (non-empty selection, not a container menu):
///   Create Alias, Lock, Unlock, Copy Name, Copy Path, Copy File URL, Cut
/// Container background:
///   Open Terminal, Copy Folder Name, Copy Folder Path, New File ▸,
///   New Folder, Paste Here, then the non-empty favorites submenus
///   (常用软件 ▸ / 常用网页 ▸ / 常用文件夹 ▸, each hidden when empty).
///
/// **No separator items**: a separator handed to Finder is given its slot but no
/// rule is drawn — measured on a real menu, it costs a whole blank row (~24pt)
/// while the native separators above it keep their hairline. Dropping them makes
/// the items contiguous instead of leaving gaps that read as a layout bug. Same
/// process-boundary effect as the menu images; see README "Why the Finder context
/// menu has no icons".
enum FinderMenuBuilder {
    static func plan(
        for selection: FinderSelectionContext,
        containerMenu: Bool = false,
        hasCutPayload: Bool,
        newFileKinds: [NewFileKind] = NewFileKind.allCases,
        favorites: [FinderFavoriteEntry] = [],
        archives: FinderArchiveSelection = .none
    ) -> [FinderMenuPlanItem] {
        if !containerMenu && selection.hasSelection {
            // P9: the archive actions are the only submenus in the selection
            // menu. The alias/lock/copy/cut items stay flat — that decision was
            // about not showing a cascade for the actions the user already had;
            // 解压/压缩 have several variants each, so they need their own menu.
            var items: [FinderMenuPlanItem] = [
                .action(.createAlias(items: selection.itemURLs)),
                .action(.setLocked(items: selection.itemURLs, locked: true)),
                .action(.setLocked(items: selection.itemURLs, locked: false)),
                .action(.copyName(payload: selection.formattedNames)),
                .action(.copyPath(payload: selection.formattedPaths)),
                .action(.copyFileURL(payload: selection.formattedFileURLs)),
                .action(.cut(items: selection.itemURLs)),
            ]
            if archives.canExtract {
                items.append(.submenu(titleKey: .finderMenuExtract, actions: [
                    .extractArchives(archives: archives.archives, destination: nil),
                    .extractArchivesCustomize(archives: archives.archives),
                ]))
            }
            if archives.canCompress {
                var compressionItems = FinderArchives.compressionFormats.map {
                    FinderMenuAction.compressItems(items: archives.compressible, format: $0)
                }
                compressionItems.append(.compressItemsCustomize(items: archives.compressible))
                items.append(.submenu(titleKey: .finderMenuCompress, actions: compressionItems))
            }
            return items
        }

        guard let container = selection.containerDirectory else { return [] }

        // P7-b: the three favorites submenus, in product-spec order, each hidden
        // when it has nothing to show (an empty submenu is a dead end, and the
        // spec asks for "空时隐藏").
        let apps = favorites.filter { $0.kind == .application }.map { FinderMenuAction.openFavorite(entry: $0) }
        let websites = favorites.filter { $0.kind == .website }.map { FinderMenuAction.openFavorite(entry: $0) }
        let folders = favorites.filter { $0.kind == .folder }.map { FinderMenuAction.openFavorite(entry: $0) }
        var favoritesItems: [FinderMenuPlanItem] = []
        if !apps.isEmpty { favoritesItems.append(.submenu(titleKey: .categoryFavoriteApps, actions: apps)) }
        if !websites.isEmpty { favoritesItems.append(.submenu(titleKey: .categoryFavoriteWebsites, actions: websites)) }
        if !folders.isEmpty { favoritesItems.append(.submenu(titleKey: .categoryFavoriteFolders, actions: folders)) }

        return [
            .action(.openTerminal(directory: container)),
            .action(.copyFolderName(payload: container.lastPathComponent)),
            .action(.copyFolderPath(payload: container.path)),
            .submenu(titleKey: .categoryNewFile, actions: newFileKinds.map { kind in
                .newFile(kind: kind, directory: container)
            }),
            .action(.newFolder(directory: container)),
            .action(.pasteHere(destination: container, enabled: hasCutPayload)),
        ] + favoritesItems
    }
}
